### ISSUE TITLE
Crash in pybar_fei4_histogrammer due to timestamp_stop

### ISSUE THREAD

**Issue by YannickDieter** [SiLab-Bonn/silab_online_monitor#6]
```
Traceback (most recent call last):
  File "/home/silab/miniconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/silab/git/online_monitor/online_monitor/converter/transceiver.py", line 165, in run
    data = self.interpret_data(raw_data)
  File "/home/silab/git/silab_online_monitor/silab_online_monitor/converter/pybar_fei4_histogrammer.py", line 56, in interpret_data
    now = float(meta_data['timestamp_stop'])
KeyError: 'timestamp_stop'
```

**Comment by DavidLP** [comment]
Still happening?

**Comment by laborleben** [comment]
Well I can't say, since you are the only one observing this. The commit https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/commit/7c93ea5d7d2f8e22502e569052c642822f8c10d1 is hiding any any "issue" with the timestamp. I put issue into quotation marks, because it is not a real issue, and any crashing was prevented by you commits.
I anyway suspect that this is a platform issue, because I never saw this on Linux in several years of operating the readout system.
I'd like to see this closed as well as https://github.com/SiLab-Bonn/pyBAR/issues/48.

**Comment by DavidLP** [comment]
I do not think that [SiLab-Bonn/pyBAR#48](https://github.com/SiLab-Bonn/pyBAR/issues/48) is related. This issue here is a not existing key and not a wrong value. Also [SiLab-Bonn/pyBAR#48](https://github.com/SiLab-Bonn/pyBAR/issues/48) still happens, thus needs a fix at some point or should at least be documented as unsolved. Thus is should be an open issue,
