### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/silab_online_monitor#7]
The python 3 compatibility got lost. [Unit tests](https://travis-ci.org/SiLab-Bonn/silab_online_monitor/jobs/220859817) fail in the serializer functions in the underlying generic online_monitor package:

``` bash
Process DUT0:

Traceback (most recent call last):

  File ".../python3.6/multiprocessing/process.py", line 249, in _bootstrap

    self.run()

  File ".../python3.6/site-packages/online_monitor/converter/transceiver.py", line 167, in run

    self.send_data(data)

  File ".../python3.6/site-packages/online_monitor/converter/transceiver.py", line 137, in send_data

    serialized_data = serialized_data.encode('utf-8')

AttributeError: 'array.array' object has no attribute 'encode'
```

**Comment by DavidLP** [comment]
No sure if this is fixed in development branch of `online_monitor` already. Then a new release is needed.
